# Generated by Django 5.0.3 on 2024-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_country_alter_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed'), ('R', 'Payment Received'), ('S', 'Shipped')], default='P', max_length=1),
        ),
    ]
