# Generated by Django 5.0.3 on 2024-05-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_strip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='strip_id',
            field=models.CharField(max_length=255),
        ),
    ]
