# Generated by Django 5.0.3 on 2024-05-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_strip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='strip_id',
            new_name='stripe_id',
        ),
    ]
